version: 0.2
env:
  parameter-store:
    AWS_ACCESS_KEY_PROD: "devops-access-key"
    AWS_SECRET_KEY_PROD: "devops-secret-key"

phases:
  install:
    runtime-versions:
       docker: 19
    commands:
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - curl -O https://releases.hashicorp.com/terraform/1.1.4/terraform_1.1.4_linux_amd64.zip
      - unzip ./terraform_1.1.4_linux_amd64.zip -d /usr/local/bin
      - terraform -v

  pre_build:
    commands:
      - terraform init

  build:
    commands:
      - terraform validate
      - aws_credentials=$(aws sts assume-role --role-arn "arn:aws:iam::*******:role/Cross-Account-Dev" --role-session-name "RoleSession1") #DevOps account crossaccount role ARN
      - export AWS_ACCESS_KEY_ID=$(echo $aws_credentials|jq '.Credentials.AccessKeyId'|tr -d '"')
      - export AWS_SECRET_ACCESS_KEY=$(echo $aws_credentials|jq '.Credentials.SecretAccessKey'|tr -d '"')
      - export AWS_SESSION_TOKEN=$(echo $aws_credentials|jq '.Credentials.SessionToken'|tr -d '"')
      - terraform plan -out=plan.tf

  post_build:
    commands:
      - echo build completed on 'date'

artifacts:
    files:
        - '**/*'
